### ISSUE TITLE
target labels are seem to be leaked in training

### ISSUE THREAD

**Issue by geoffrey007** [chaoqichen/HTCN#8]
Hi @chaoqichen 

Thanks for your interesting work and sharing code!

I was wondering whether the labels of target images are leaked in optimizing `d_ins` loss.
`d_ins` loss is calculated from `rois`. However, `gt_boxes` are added to `rois` via `RCNN_proposal_target` during training.

https://github.com/chaoqichen/HTCN/blob/90f7f9c0b650215c87b9018aef6c8f87dec23854/lib/model/faster_rcnn/faster_rcnn_HTCN.py#L92-L98

https://github.com/chaoqichen/HTCN/blob/90f7f9c0b650215c87b9018aef6c8f87dec23854/lib/model/rpn/proposal_target_layer_cascade.py#L42-L43

**Comment by chaoqichen** [comment]
Hi @geoffrey007 

Thank you for pointing out this problem. We should note that we did not leverage the target labels for training any classification and regression losses. The target labels were unexpectedly used for choosing ROIs (including positive and negative samples), while we can also randomly choose the ROIs. The only difference is that using target labels will roughly make the proportion of positive and negative samples fixed in the target domain. However, such operation was used in the conventional Faster R-CNN for training classificaiton and regression losses. In our paper, the adversarial training loss (**L_ins**) did not require the GT labels, so the benefit of the GT labels can be neglected (or even **bringing negative influence**). 

The possible justification is that the adverarial training loss should be focused on the positive samples, however, using GT labels for choosing ROIs will make the amount of positive samples limited. For example, in our case, their ratio is about 1 : 3 (positive : negative). By contrast, if we randomly choose the ROIs, the ratio of positive samples may be higher.  

We conduct an additional experiment on _PASCAL VOC 2 Clipart_ by randomly choosing the ROIs, the mAP is **40.52**, which is higher than the reported results (**40.3**). Thus, we will revise our source code, and we do appreaciate your helping. BTW, it is an interesting question to compare these two differences in-depth.  

Moreover, we note that a recent CVPR 2020 paper also take the same [operation](https://github.com/ChrisAllenMing/GPA-detection/blob/34a987ac9b71718f6d66465078a9d8ec9f9482c7/train_GPA.py#L484).

**Comment by geoffrey007** [comment]
Get it! Thanks for your quick response!
